name: unit-tests

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   ci:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@master

         - name: Setup node env
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: npm

         - name: Install dependencies
           run: npm install

         - name: Run harhat unit test
           run: npx hardhat test

   coverage:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v3
           with:
              fetch-depth: 2
         - name: Setup
           uses: actions/setup-node@v3
           with:
              node-version: 12.x
         - name: Cache
           uses: actions/cache@v3
           id: cache
           with:
              path: "**/node_modules"
              key: npm-v2-${{ hashFiles('**/package-lock.json') }}
              restore-keys: npm-v2-
         - name: Test
           run: npx hardhat test
           env:
              NODE_OPTIONS: --max_old_space_size=4096
         - name: Codecov
           uses: codecov/codecov-action@v3
